CREATE TABLE IF NOT EXISTS books (  /* PLURAL Y ABAJO YA SINGULAR, BUENA PRACTICA QUE CUANDO NO ES TU CÓDIGO MAYUSCULAS Y SI ES TUYO MINUSCULAS, AUNQUE ACEPTE CUALQUIERA */
    `book_id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,  /* ENTERO Y QUE SE CREE UN ID DE FORMA INCREMENTAL AUTOMÁTICAMENTE EN CADA FILA, SI SE BORRA UNA FILA SE VA A CREEAR UN EL NÚMERO SIGUIENTE AL ÚLTIMO QUE SE DIÓ, INDEPENTIENDTEMENTE DE QUE SE HAYAN BORRADO FILAS */
    `author_id` INT UNSIGNED,  /* ENTERO Y NO SE PUEDE REPETIR */
    `title` VARCHAR(100) NOT NULL,  /* CADENA CON CIERTA CANTIDAD DE CARACTERES Y QUE SIEMPRE SEA REQUERIDO  */
    `year` INT UNSIGNED NOT NULL DEFAULT 1900,  /* ENTERO, SIN REPETIRSE, REQUERIDO Y SI NO SE LE DA VALOR TIENE UNO POR DEFAULT */
    `language` VARCHAR(2) NOT NULL DEFAULT 'es' COMMENT 'ISO 639-1 Language',  /* CADENA DE 2 CARACTERES,REQUERIDA, POR DEFAULT ES Y CON UN COMENTARIO */
    `cover_url` VARCHAR(500),
    `price` DOUBLE NOT NULL DEFAULT 10.0,  /* TIPO NUMÉRICO BASE DOS, AL DAR DECIMALES REDONDEA Y NO DEJA QUE SEAN DECIMALES LARGOS, CONTRARIO A FLOAT*/
    `sellable` TINYINT DEFAULT 1,  /* TIPO BOOLEANO Y DA UN VALOR POR DEFAULT SI NO SE LE DA NINGUN VALOR */
    `copies` INT NOT NULL DEFAULT 1,
    `description` TEXT  /* TEXTO NORMAL SIN RESTRICCIÓN DE CARACTERES */
);

CREATE TABLE IF NOT EXISTS authors(
    `author_id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `nationality` VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS clients(
    `client_id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) NOT NULL UNIQUE,
    `birthdate` DATETIME,  /* RECUPERA LA FECHA DE ACUERDO AL PAIS DONDE SE ESTA LLENANDO */
    `gender` ENUM('M','F', 'ND') NOT NULL,  /* ENUMERA OPCIONES A ELEGIR, SÓLO PUEDE ELEGIR UNA Y ES REQUERIDA*/
    `active` TINYINT(1) NOT NULL DEFAULT 1,  /* ES BUENA PRÁCTICA TENER UNA COLUMNA CON ESTE NOMBRE PARA ACTIVAR O DESACTIVAR FILAS(INFORMACIÓN), NO SE DEBERÍAN BORRAR */
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  /* SI NO DA UN DATO INSERTA LA HORA DEL SERVIDOR */
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP /* TE DA LA FECHA DE CUANDO SE ACTUALIZÓ LA INFORMACIÓN */
);

CREATE TABLE IF NOT EXISTS operations(
    `operations_id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `book_id` INT UNSIGNED NOT NULL,
    `client_id` INTEGER UNSIGNED NOT NULL,
    `type` ENUM ('V', 'P', 'D') NOT NULL COMMENT 'V: Vendido -P:Prestado -D: Devuelto',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `finished` TINYINT(1) NOT NULL
);